### ISSUE TITLE
AttributeError: module 'gym.wrappers' has no attribute 'SkipWrapper'

### ISSUE THREAD

**Issue by ibiscp** [llSourcell/Landing-a-SpaceX-Falcon-Heavy-Rocket#4]
Can anyone help me with this error?

```
Traceback (most recent call last):
  File "ppo.py", line 63, in <module>
    env = GymEnvironment(env_name=env_name, log_path="./PPO_log", skip_frames=5)
  File "/Landing-a-SpaceX-Falcon-Heavy-Rocket-master/agents/environment.py", line 24, in __init__
    frameskip_wrapper = gym.wrappers.SkipWrapper(skip_frames)
AttributeError: module 'gym.wrappers' has no attribute 'SkipWrapper'
```

**Comment by Fellfalla** [comment]
After running `pip install gym-wrappers` it doesn't work either
